services:
  express-app:
    image: einsteinium1/devops-express-app:latest
    container_name: express-app
    ports:
      - 8080:8080

  watchtower:
    image: containrrr/watchtower
    command: --interval 60 express-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
